app/login/__init__.py
from flask import Blueprint

login_bp = Blueprint('login', __name__, url_prefix='/login')

from app.login import routes

app/login/routes.py
import json
<<<<<<< HEAD
from flask import render_template, redirect, request, flash
=======
from flask import render_template, redirect, request, flash, session, url_for
>>>>>>> hershil
from app.login import login_bp
from app.api import users, hashing
# from flask_login import current_user, login_user

@login_bp.route('/login_page',methods=['GET','POST'])
def login_page():
    error = None
<<<<<<< HEAD
=======
    error1 = "Email"
    error2 = "Password"
>>>>>>> hershil

    if request.method == "POST":
        email = request.form.get('email', False)

        password = request.form.get('password', False)
        to_hash = {
            "password": password
        }
        hash = hashing.hash_password(json.dumps(to_hash))
        info = json.loads(hash)
        pH = info["passwordhash"]

        info = {
            "email": email,
            "passwordhash": pH
        }

        json_info = json.dumps(info)
        user = users.get_user(json_info)
<<<<<<< HEAD

        if(user == False):
            error = "Login information is incorrect"
=======
        if (user == False):
            error1 = "Login information is incorrect!"
            error2 = "Login information is incorrect!"
>>>>>>> hershil
            info = {
                "status": "Failure"
            }
        else:
<<<<<<< HEAD
            error = "Success"
            info = {
                "status": "Success",
                "userName": user
            }
        #return json.dumps(info)

    return render_template("login.html", error=error)
=======
            error = None
            session['userid'] = user
            return redirect(url_for('index'))

    return render_template("login.html", error=error, error1=error1, error2=error2)

@login_bp.route('/logout', methods=['GET','POST'])
def logout():
    session.pop('userid', None)
    return redirect(url_for('index'))
>>>>>>> hershil

app/recommend/__init__.py
from flask import Blueprint

recommend_bp = Blueprint('recommend', __name__, url_prefix='/recommend')

from app.recommend import routes

app/recommend/routes.py
from flask import Flask, render_template, request, redirect
from werkzeug.utils import secure_filename
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
import smtplib, ssl, email
from app.recommend import recommend_bp


@recommend_bp.route('/email')  # would take recommendation from users to add a movie that not currently in database
def recommendation():
    return render_template('recommend.html')


@recommend_bp.route('/recommend_check', methods=['POST', 'GET'])
def recommend_confirm():  # take form and send email to people
    if request.method == 'POST':
        result = request.form
        m_name = result['movie_name']
        receiver_email = "crunchmovietest@gmail.com"
        user = result['user']
        subject = "Movie Recommendation: %s" % (m_name)
        email = result['msg']

        sender_email = "crunchmovietest@gmail.com"
        message = MIMEMultipart()
        text = """\
        User: %s
        Movie name: %s

        Why should it be added:
        %s""" % (
        user, m_name, email)  # add other things if needed, such as country of origin or what studio make the movie/when
        message.attach(MIMEText(text, 'plain'))
        message["Subject"] = subject
        message["From"] = sender_email
        message["To"] = receiver_email

        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(sender_email, 'crunchtest123')
            server.sendmail(sender_email, receiver_email, message.as_string())

    return render_template('confirmation.html')

app/search/__init__.py
from flask import Blueprint

search_bp = Blueprint('search', __name__, url_prefix='/search')

from app.search import routes

app/search/routes.py
from app.search import search_bp
import json
from flask import render_template, redirect, url_for
from flask import request
<<<<<<< HEAD
from app.api import movie_search
=======
from app.api import movie_search, web_scraper, Comments
>>>>>>> hershil


@search_bp.route('/search_page', methods=["GET", "POST"])
def search_page():
    error = None
<<<<<<< HEAD
=======
    data = None
>>>>>>> hershil
    if request.method == "POST":
        search_criteria = request.form.get('search_criteria', False)

        info = {
            "search": search_criteria
        }

        data = movie_search.search_movie(json.dumps(info))

        if(data == {}):
            error = "No movies of that title exist!"
            state = {
                "status": error
            }
            return json.dumps(state)
        else:
            #return data


            return redirect(url_for("search.search_results_page", data=data))
<<<<<<< HEAD
    return render_template("search.html", error=error)
=======
    return render_template("search_results.html", data=data)
>>>>>>> hershil

@search_bp.route('/search_results_page', methods=["GET", "POST"])
def search_results_page():
    data = request.values.get('data')
    loaded_data = json.loads(data)
<<<<<<< HEAD
    return render_template("search_results.html", data=loaded_data)
=======
    return render_template("search_results.html", data=loaded_data)

@search_bp.route('/movie_details_page', methods=["GET", "POST"])
def movie_details_page():
    movie_title = request.values.get('title')
    is_adult = request.values.get('isAdult')
    start_year = request.values.get('startYear')
    runtime = request.values.get('runtime')
    genres = request.values.get('genres')
    movieID = request.values.get('id')
    comments = Comments.get_comment(movieID)

    info = {
        "titleID": movieID
    }

    scraped_data = web_scraper.get_movie_info(json.dumps(info))
    loaded_scraped_data = json.loads(scraped_data)

    crew_data = movie_search.get_cast(json.dumps(info))
    loaded_crew_data = json.loads(crew_data)



    poster_link = loaded_scraped_data["posterLink"]
    plot_text = loaded_scraped_data["plotText"]

    cast = {}
    for i in loaded_crew_data:
        cast[loaded_crew_data[i]["name"]] = {
            "name": loaded_crew_data[i]["name"],
            "category": loaded_crew_data[i]["category"],
            "job": loaded_crew_data[i]["job"],
            "characters": loaded_crew_data[i]["characters"]
        }


    return render_template('movie_details.html', movie_title=movie_title, start_year=start_year,
                           runtime=runtime, genres=genres, poster_link=poster_link, plot_text=plot_text, cast=cast, movieID=movieID, comments=comments)



>>>>>>> hershil

app/signup/__init__.py
from flask import Blueprint

signup_bp = Blueprint('signup', __name__, url_prefix='/signup')

from app.signup import routes

app/signup/routes.py
import json
from flask import render_template, request, flash, redirect, url_for
from app.signup import signup_bp
from app.api import users,hashing
import hashlib



@signup_bp.route('/signup_page', methods=['POST', 'GET'])
def signup_page():

    error = None
<<<<<<< HEAD
=======
    error1 = "Email"
    error2 = "Username"
>>>>>>> hershil

    if request.method == 'POST':
        fullname = request.form.get('fullName', False)
        email = request.form.get('email', False)
        username = request.form.get('username', False)

        password = request.form.get('password', False)
        to_hash = {
                "password" : password
        }
        hash = hashing.hash_password(json.dumps(to_hash))
        info = json.loads(hash)
        passwordhash = info["passwordhash"]

        info = {
            "email": email,
            "userName": username,
            "passwordHash": passwordhash,
            "fullName": fullname
        }
        json_info = json.dumps(info)
        check = users.check_user(json_info)


        if(check == 'clear'):
            users.create_user(json_info)
<<<<<<< HEAD
            error = "Account successfully created!"
            info = {
                "status": "success"
            }
        elif(check == 'email taken'):
            error = "The email is already taken!"
=======
            error = None
            return redirect(url_for('login.login_page'))
        elif(check == 'email taken'):
            error1 = "The email is already taken!"
>>>>>>> hershil
            info = {
                "status": "email taken"
            }
        elif(check == 'username taken'):
<<<<<<< HEAD
            error = "The username is already taken!"
=======
            error2 = "The username is already taken!"
>>>>>>> hershil
            info = {
                "status": "username taken"
            }
        #return json.dumps(info)

<<<<<<< HEAD
    return render_template('signup.html', error=error)
=======
    return render_template('signup.html', error=error, error1=error1, error2=error2)
>>>>>>> hershil

app/support/__init__.py
from flask import Blueprint

support_bp = Blueprint('support', __name__, url_prefix='/support')

from app.support import routes

app/support/routes.py
from flask import Flask, render_template, request, redirect, url_for
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
import smtplib, ssl, email
import os
import datetime
import csv
from app.support import support_bp
from app.api import tickets
import json


@support_bp.route('/create_ticket')  # create support ticket page
def support_ticket():
    return render_template('support.html')


@support_bp.route('/support_confirm', methods=['POST', 'GET'])
def support_confirm():  # would take previous form create a ticket
    if request.method == 'POST':
        result = request.form
        receiver_email = ("crunchmovietest@gmail.com", result['email'])
        sender_email = "crunchmovietest@gmail.com"
        time = datetime.datetime.now().strftime("%Y%m%d%I%M%S")  # create ticket number
        subject = "Support ticket #%s" % (time)
        email = result['message']
        user = result['user']



        for x in receiver_email:  # would send to our and their email
            message = MIMEMultipart()
            text = """
                    User: %s

                    %s""" % (user, email)
            message.attach(MIMEText(text, 'plain'))
            message["Subject"] = subject
            message["From"] = sender_email
            message["To"] = x
            context = ssl.create_default_context()  # send email
            with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
                server.login(sender_email, 'crunchtest123')
                server.sendmail(sender_email, x, message.as_string())

        info = {
            "user": user,
            "ticket_id": time
        }
        tickets.create_ticket(json.dumps(info))
        # with open('support.txt', mode='a') as support:  # add new support ticket to csv
        #     support_writer = csv.writer(support, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        #     support_writer.writerow([time, user, 'Unresolved'])
        # with open('support.txt', 'r') as f:  # create list with csv and sort
        #     reader = csv.reader(f)
        #     your_list = list(reader)
        # your_list.sort(reverse=True)
        # with open('support.txt', mode='w') as a:  # write csv with updated list
        #     writer = csv.writer(a)
        #     writer.writerows(your_list)
    return render_template('confirmation.html')

#admin only
@support_bp.route('/support_ticket')  # look at list and allow to set a ticket to resolved
def support_check():
    # with open('support.txt', 'r') as f:  # create list with csv and sort
    #     csv_reader = csv.reader(f, delimiter=',')
    #     ticket = list(csv_reader)
    # ticket.sort(reverse=True)
    ticket = json.loads(tickets.get_tickets())
    return render_template('support_ticket.html', ticket=ticket)

#admin only
@support_bp.route('/support_resolved', methods=['POST', 'GET'])
def support_remove():  # takes ticket number and set it to resolved
    if request.method == 'POST':
        result = request.form
        ticket = result['ticket']

        info = {
            "ticketID": ticket
        }

        tickets.update_ticket(json.dumps(info))
        # with open('support.txt', 'r') as f:
        #     reader = csv.reader(f)
        #     your_list = list(reader)
        # for x in your_list:
        #     if ticket == x[0]:
        #         x[0] = ticket
        #         x[2] = 'Resolved'
        #     else:
        #         pass
        # with open('support.txt', mode='w') as support:  # write csv with updated list
        #     writer = csv.writer(support)
        #     writer.writerows(your_list)
    return render_template('confirmation2.html')

app/templates/confirmation.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta http-equiv="refresh" content="3;url={{ url_for('index') }}"/>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Welcome to Crun.ch.</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
   <link href="../static/css/recommendstyle.css" rel="stylesheet">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14
   .7/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>

<body style="background-color: black">
<div class="container" style="background:#000000" align="center">
	<h1>Message Sent!</h1>
</div>
</body>
</html>
{% endblock %}

app/templates/confirmation2.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta http-equiv="refresh" content="3;url={{ url_for('support.support_check') }}"/>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Welcome to Crun.ch.</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
   <link href="../static/css/recommendstyle.css" rel="stylesheet">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14
   .7/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>

<body style="background-color: black">
<div class="container" style="background:#000000" align="center">
	<h1>Status Updated!</h1>
</div>
</body>
</html>
{% endblock %}

app/templates/email_result.html
{% block content %}
<html>
    <head>
        <p>Comfirmation page</p>
    </head>
    <body>
        <p>Email sent</p>

    </body>
</html>
{% endblock %}

app/templates/index.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap - Prebuilt Layout</title>

<!-- Bootstrap -->
<link href="../static/css/homestyle.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body bgcolor="#000000">

<!-- Header -->
<div class="header">
  <div class="logo">
  	<img src="../static/images/logo2.png" width="275" height="60" alt=""/>
  </div>
  <div class="search">
  	<form class="search" action="../search/search_page" method="POST" style="justify-content: center; padding-top: 15px; padding-left: 80px;">
		<div class="form-group">
			<input type="text" id="search" class="form-control" name="search_criteria" placeholder="Search...">
		</div>
	</form>
  </div>
  <div class="submit">
  	<form class="search_button" action="../search/search_page" method="POST" style="justify-content: center; padding-top: 16px; padding-left: 10px;">
		<button type="submit" name="search" > Submit </button>
	</form>
  </div>
  {% if username == None %}
      <div class="login" style="padding-top: 16px; padding-left: 1045px">
        <form class="login" action="../login/login_page">
            <button type="submit" name="search"> Login </button>
        </form>
      </div>
      <div class="signup" style="padding-top: 16px; padding-left: 5px;">
        <form class="signup" action="../signup/signup_page">
            <button type="submit" name="search"> Sign Up </button>
        </form>
      </div>
  {% else %}
      <div class="profile_pic" style="padding-top: 16px; padding-left: 1050px">
          <img src="../static/images/blank_profile.png" width="25" height="25">
      </div>
      <div class="profile_link" style="padding-top: 20px; padding-left: 5px;">
          <a href="../profile/profile_page" style="color: white; font-size: 20px;">{{ username }}</a>
      </div>
      <div class="logout" style="padding-top: 16px; padding-left: 5px;">
        <form class="logout" action="../login/logout">
            <button type="submit" name="logout" style="font-size: 20px;"> Logout </button>
        </form>
      </div>
  {% endif %}
</div>

<!-- Navigation Bar -->
<div class="navbar">
    <h3 style="color: white;">The <b style="color: #D4AF37">BEST</b> place to get all of your movie needs.  <b style="color: #D4AF8F">Get Crunchin'</b></h3>
</div>

<!-- The flexible grid (content) -->
<div class="row">
  <div class="side">
    <h2>Upcoming Movies</h2>
    <a style="color:#D4AF8F" href="http://127.0.0.1:5000/search/movie_details_page?title=Avengers%3A+Endgame&id=tt4154796&isAdult=0&startYear=2019&genres=Action%2CAdventure%2CFantasy&runtime=181"><h4 style="text-decoration: underline">Avengers: Endgame</h4></a>
    <a href="http://127.0.0.1:5000/search/movie_details_page?title=Avengers%3A+Endgame&id=tt4154796&isAdult=0&startYear=2019&genres=Action%2CAdventure%2CFantasy&runtime=181"><img src="../static/images/endgame poster.jpg" style="width:100%"></a>
    <p style="font-size: 15px;">Coming out April 26th, this monumental superhero movie ends the decade long MCU journey.  And so the hole in my life returns...</p>
    <a style="color:#D4AF8F" href="http://127.0.0.1:5000/search/movie_details_page?title=Pok%C3%A9mon+Detective+Pikachu&id=tt5884052&isAdult=0&startYear=2019&genres=Action%2CAdventure%2CComedy&runtime=104"><h4 style="text-decoration: underline">Pokemon Detective Pikachu</h4></a>
    <a href="http://127.0.0.1:5000/search/movie_details_page?title=Pok%C3%A9mon+Detective+Pikachu&id=tt5884052&isAdult=0&startYear=2019&genres=Action%2CAdventure%2CComedy&runtime=104"><img src="../static/images/detective pikachu poster.jpg" style="width:100%"></a>
    <p style="font-size: 15px;">Coming out May 10th, this noir detective comedy brings life to the pokemon world, hopefully it's as good as it looks.</p>
    <a style="color:#D4AF8F" href="http://127.0.0.1:5000/search/movie_details_page?title=Toy+Story+4&id=tt1979376&isAdult=0&startYear=2019&genres=Adventure%2CAnimation%2CComedy&runtime=%5CN"><h4 style="text-decoration: underline">Toy Story 4</h4></a>
    <a href="http://127.0.0.1:5000/search/movie_details_page?title=Toy+Story+4&id=tt1979376&isAdult=0&startYear=2019&genres=Adventure%2CAnimation%2CComedy&runtime=%5CN"><img src="../static/images/toy story 4 poster.jpg" style="width:100%"></a>
    <p style="font-size: 15px;">Coming out June 21th, if it's anything like the last one, don't bring your kids; it's dangerous to drive while crying.</p>
    <a style="color:#D4AF8F" href="http://127.0.0.1:5000/search/movie_details_page?title=Once+Upon+a+Time+in+Hollywood&id=tt7131622&isAdult=0&startYear=2019&genres=Comedy%2CDrama&runtime=%5CN"><h4 style="text-decoration: underline">Once Upon a Time in Hollywood</h4></a>
    <a href="http://127.0.0.1:5000/search/movie_details_page?title=Once+Upon+a+Time+in+Hollywood&id=tt7131622&isAdult=0&startYear=2019&genres=Comedy%2CDrama&runtime=%5CN"><img src="../static/images/hollywood poster.jpg" style="width:100%"></a>
    <p style="font-size: 15px;">Coming out July 26th, Tarantino's 9th film follows a faded television actor and his stunt double on their quest to fame and success in the final years of Hollywood's Golden Age.</p>
  </div>
  <div class="main">
    <h2 style="text-align: center">Trending Movies</h2>
    <h4 style="text-align: center">Hottest movies in theaters now!</h4>
		<!-- Slideshow container -->
	<div class="slideshow-container">
  		<div class="mySlides1">
   			<div class="numbertext">1 / 4</div>
            <a href="http://127.0.0.1:5000/search/movie_details_page?title=Shazam%21&id=tt0448115&isAdult=0&startYear=2019&genres=Action%2CAdventure%2CComedy&runtime=132"><img src="../static/images/shazam.jpg" style="width:100%"></a>
    		<div class="text">Shazam</div>
  		</div>

  		<div class="mySlides1">
   			<div class="numbertext">2 / 4</div>
            <a href="http://127.0.0.1:5000/search/movie_details_page?title=Pet+Sematary&id=tt0837563&isAdult=0&startYear=2019&genres=Horror%2CMystery%2CThriller&runtime=101"><img src="../static/images/pet sematary poster.jpeg" style="width:100%"></a>
    		<div class="text">Pet Sematary</div>
  		</div>

  		<div class="mySlides1">
   			<div class="numbertext">3 / 4</div>
            <a href="http://127.0.0.1:5000/search/movie_details_page?title=Missing+Link&id=tt6348138&isAdult=0&startYear=2019&genres=Adventure%2CAnimation%2CComedy&runtime=95"><img src="../static/images/missing link poster.jpg" style="width:100%"></a>
    		<div class="text">Missing Link</div>
  		</div>

  		<div class="mySlides1">
   			<div class="numbertext">4 / 4</div>
            <a href="http://127.0.0.1:5000/search/movie_details_page?title=Us&id=tt6857112&isAdult=0&startYear=2019&genres=Horror%2CThriller&runtime=116"><img src="../static/images/us-poster-social.jpg" style="width:100%"></a>
    		<div class="text">Us</div>
  		</div>

  		<a class="prev" onclick="plusSlides(-1, 0)">&#10094;</a>
  		<a class="next" onclick="plusSlides(1, 0)">&#10095;</a>
	</div>
	<br>
    <br>
    <h2 style="text-align: center">Staff Picks</h2>
    <h4 style="text-align: center">The best movies chosen by our staff!</h4>
    <div class="slideshow-container">
		<div class="slideshow-container">
  		<div class="mySlides2">
	    	<div class="numbertext">1 / 3</div>
            <a href="http://127.0.0.1:5000/search/movie_details_page?title=Deadpool&id=tt1431045&isAdult=0&startYear=2016&genres=Action%2CAdventure%2CComedy&runtime=108"><img src="../static/images/deadpool poster.jpg" style="width:100%"></a>
		    <div class="text">Deadpool</div>
  		</div>

  		<div class="mySlides2">
   			<div class="numbertext">2 / 3</div>
            <a href="http://127.0.0.1:5000/search/movie_details_page?title=The+Big+Lebowski&id=tt0118715&isAdult=0&startYear=1998&genres=Comedy%2CCrime&runtime=117"><img src="../static/images/big lebowski poster.jpg" style="width:100%"></a>
    		<div class="text">The Big Lebowski</div>
  		</div>

  		<div class="mySlides2">
   			<div class="numbertext">3 / 3</div>
            <a href="http://127.0.0.1:5000/search/movie_details_page?title=Hauru+no+ugoku+shiro&id=tt0347149&isAdult=0&startYear=2004&genres=Adventure%2CAnimation%2CFamily&runtime=119"><img src="../static/images/howls poster.jpg" style="width:100%"></a>
    		<div class="text">Howl's Moving Castle</div>
  		</div>

  		<a class="prev" onclick="plusSlides(-1, 1)">&#10094;</a>
  		<a class="next" onclick="plusSlides(1, 1)">&#10095;</a>
	</div>
	<br>
  </div>
</div>

<!-- Footer -->
<div class="footer">
	<h2>Helpful links</h2>
	<a href="{{ url_for('recommend.recommendation') }}" style="color:white;">Recommend a movie</a>
 	<a href="{{ url_for('support.support_ticket') }}" style="color:white;">Support</a>
</div>

<script>
	var slideIndex = [1,1];
	/* Class the members of each slideshow group with different CSS classes */
	var slideId = ["mySlides1", "mySlides2"]
	showSlides(1, 0);
	showSlides(1, 1);

	function plusSlides(n, no)
	{
	  showSlides(slideIndex[no] += n, no);
	}

	function showSlides(n, no)
	{
	  var i;
	  var x = document.getElementsByClassName(slideId[no]);
	  if (n > x.length) {slideIndex[no] = 1}
	  if (n < 1) {slideIndex[no] = x.length}
	  for (i = 0; i < x.length; i++) {
		x[i].style.display = "none";
	  }
	  x[slideIndex[no]-1].style.display = "block";
	}
</script>

</body>
</html>
{% endblock %}

app/templates/search_results.html
{% block content %}
<<<<<<< HEAD
<html>
    <h1>Welcome! Search for movies here!</h1>
    <body>
        <form action = '/search/search_page' method="POST">
            Search: <input type="text" name="search_criteria"> <input type="submit" value="Search">
        </form>
        <ul style="list-style-type: none">
            {% for i in data %}
                <li>
                    {{ data[i]["title"] }}, {{ data[i]["startYear"] }} ({{ data[i]["genres"] }})
                </li>
            {% endfor %}
        </ul>
    </body>
</html>
{% endblock %}
=======
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap - Prebuilt Layout</title>

<!-- Bootstrap -->
<link href="../static/css/searchstyle.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body bgcolor="#000000">

	<!-- Header -->
	<div class="header">
	  <div class="logo">
		<a href="{{ url_for('index') }}"><img src="../static/images/logo2.png" width="275" height="60" alt=""/></a>
	  </div>
	  <div class="search">
		<form class="search" action="../search/search_page" method="POST" style="justify-content: center; padding-top: 15px; padding-left: 1300px;">
			<div class="form-group">
				<input type="text" id="search" class="form-control" name="search_criteria" placeholder="Search...">
			</div>
		</form>
	  </div>
	  <div class="submit">
		<form style="justify-content: center; padding-top: 16px; padding-left: 10px;">
			<button type="submit" name="search" > Submit </button>
		</form>
	  </div>
	</div>

	<!-- Navigation Bar -->
	<div class="navbar">
	  <a href="#">Link</a>
	  <a href="#">Link</a>
	  <a href="#">Link</a>
	  <a href="#">Link</a>
	</div>

	<div class="main">
		<div class="container2" align="center">
            <div class="table" align="left" style="background-color: #181818; ">
                {% if data != None %}
                    <h1 style="color: white; text-decoration: underline">Titles</h1>
                    <table style="align-content: center" width="100%">
                        {% for i in data %}
                            <tr>
                                <td><a href = "{{ url_for('search.movie_details_page', title=data[i]["title"], id=data[i]["movieID"], isAdult=data[i]["isAdult"], startYear=data[i]["startYear"], genres=data[i]["genres"], runtime=data[i]["runtime"]) }}" style="color: white">{{ data[i]["title"] }}, {{ data[i]["startYear"] }} ({{ data[i]["genres"] }})</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
	</div>
</body>
</html>
{% endblock %}
>>>>>>> hershil

app/templates/support_confirm.html
{% block content %}
<html>
    <head>
        <p>Comfirmation page</p>
    </head>
    <body>
        <p>Email sent</p>
    </body>
</html>
{% endblock %}